# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
dfreelon_dsc = 'This file is an archive of Twitter data in CSV format generated by'\
  ' Deen Freelon on Saturday, February 11, 2012 from a set of tweets originally'\
  ' collected by the TwapperKepper sevice prior to March 20, 2011. The left column'\
  ' contains unique Twitter message IDs, while the right column contains unique'\
  ' Twitter user IDs. Information on how to retrieve a complete set of metadata'\
  ' for each tweet based on its unique ID can be found here:'\
  ' https://dev.twitter.com/docs/api/1/get/statuses/show/:id'\
  ' Deen Freelon, Ph.D.'\
  ' dfreelon@gmail.com'\
  ' @dfreelon'\
  ' dfreelon.org'\ 

DataSet.create(name: 'dfreelon algeria', :description => dfreelon_dsc, source: 'dfreelon.org', filename: 'algeria_ids.csv')
DataSet.create(name: 'dfreelon bahrain', :description => dfreelon_dsc, source: 'dfreelon.org', filename: 'bahrain_ids.csv')
DataSet.create(name: 'dfreelon egypt', :description => dfreelon_dsc, source: 'dfreelon.org', filename: 'egypt_ids.csv')
DataSet.create(name: 'dfreelon feb14', :description => dfreelon_dsc, source: 'dfreelon.org', filename: 'feb14_ids.csv')
